[2018-12-07 01:09:22,854] [ERROR] [xinxideMacBook-Pro.local][getdata.py - line:111] 获取activitys异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/allactivity.log'
[2018-12-07 01:09:22,855] [ERROR] [xinxideMacBook-Pro.local][getdata.py - line:146] 计算遍历覆盖率异常!float division by zero
[2018-12-07 01:09:22,909] [ERROR] [xinxideMacBook-Pro.local][getdata.py - line:45] 获取安装耗时数据异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/install_app.log'
[2018-12-07 01:09:22,910] [INFO] [xinxideMacBook-Pro.local][getdata.py - line:60] 获取冷启动数据异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/lanuch_app.log'
[2018-12-07 01:09:22,913] [ERROR] [xinxideMacBook-Pro.local][getdata.py - line:226] 获取崩溃图片异常![Errno 2] No such file or directory: 'images'
[2018-12-07 01:09:22,913] [ERROR] [xinxideMacBook-Pro.local][getdata.py - line:30] 获取登录数据异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/login_app.log'
[2018-12-07 01:10:53,531] [ERROR] [xinxideMacBook-Pro.local][getdata.py - line:226] 获取崩溃图片异常![Errno 2] No such file or directory: 'images'
[2018-12-07 01:12:45,899] [INFO] [xinxideMacBook-Pro.local][server.py - line:32] 启动服务...
[2018-12-07 01:13:04,613] [INFO] [xinxideMacBook-Pro.local][server.py - line:32] 启动服务...
[2018-12-07 01:13:04,629] [INFO] [xinxideMacBook-Pro.local][_internal.py - line:88]  * Running on http://127.0.0.1:3031/ (Press CTRL+C to quit)
[2018-12-07 01:13:04,630] [INFO] [xinxideMacBook-Pro.local][_internal.py - line:88]  * Restarting with stat
[2018-12-07 01:13:04,854] [INFO] [xinxideMacBook-Pro.local][server.py - line:32] 启动服务...
[2018-12-07 01:13:04,860] [WARNING] [xinxideMacBook-Pro.local][_internal.py - line:88]  * Debugger is active!
[2018-12-07 01:13:04,879] [INFO] [xinxideMacBook-Pro.local][_internal.py - line:88]  * Debugger PIN: 120-762-539
[2018-12-07 01:13:36,217] [INFO] [xinxideMacBook-Pro.local][client.py - line:31] 开始获取报告!
[2018-12-07 01:13:36,322] [ERROR] [xinxideMacBook-Pro.local][getdata.py - line:226] 获取崩溃图片异常![Errno 2] No such file or directory: 'images'
[2018-12-07 01:13:36,342] [INFO] [xinxideMacBook-Pro.local][_internal.py - line:88] 127.0.0.1 - - [07/Dec/2018 01:13:36] "POST /getreport HTTP/1.1" 200 -
[2018-12-07 01:13:36,343] [INFO] [xinxideMacBook-Pro.local][client.py - line:36] 服务端状态码:200
[2018-12-07 01:13:36,344] [INFO] [xinxideMacBook-Pro.local][client.py - line:40] 报告路径:/Users/xinxi/PycharmProjects/maxauto/report/reports/report_20181207011336.html
[2018-12-07 01:14:29,526] [INFO] [xinxideMacBook-Pro.local][client.py - line:31] 开始获取报告!
[2018-12-07 01:14:29,638] [ERROR] [xinxideMacBook-Pro.local][getdata.py - line:226] 获取崩溃图片异常![Errno 2] No such file or directory: 'images'
[2018-12-07 01:14:29,640] [INFO] [xinxideMacBook-Pro.local][_internal.py - line:88] 127.0.0.1 - - [07/Dec/2018 01:14:29] "POST /getreport HTTP/1.1" 200 -
[2018-12-07 01:14:29,641] [INFO] [xinxideMacBook-Pro.local][client.py - line:36] 服务端状态码:200
[2018-12-07 01:14:29,641] [INFO] [xinxideMacBook-Pro.local][client.py - line:40] 报告路径:/Users/xinxi/PycharmProjects/maxauto/report/reports/report_20181207011429.html
[2018-12-07 01:14:30,068] [INFO] [xinxideMacBook-Pro.local][_internal.py - line:88]  * Detected change in '/Users/xinxi/PycharmProjects/maxauto/config.py', reloading
[2018-12-07 01:14:30,111] [INFO] [xinxideMacBook-Pro.local][_internal.py - line:88]  * Restarting with stat
[2018-12-07 01:14:30,535] [INFO] [xinxideMacBook-Pro.local][server.py - line:32] 启动服务...
[2018-12-07 01:14:30,551] [WARNING] [xinxideMacBook-Pro.local][_internal.py - line:88]  * Debugger is active!
[2018-12-07 01:14:30,570] [INFO] [xinxideMacBook-Pro.local][_internal.py - line:88]  * Debugger PIN: 120-762-539
[2018-12-07 01:14:50,552] [INFO] [xinxideMacBook-Pro.local][client.py - line:31] 开始获取报告!
[2018-12-07 01:14:50,715] [INFO] [xinxideMacBook-Pro.local][_internal.py - line:88] 127.0.0.1 - - [07/Dec/2018 01:14:50] "POST /getreport HTTP/1.1" 200 -
[2018-12-07 01:14:50,721] [INFO] [xinxideMacBook-Pro.local][client.py - line:36] 服务端状态码:200
[2018-12-07 01:14:50,722] [INFO] [xinxideMacBook-Pro.local][client.py - line:40] 报告路径:/Users/xinxi/PycharmProjects/maxauto/report/reports/report_20181207011450.html
[2018-12-07 12:42:09,289] [ERROR] [bogon][predata.py - line:68] 获取页面数据异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/page.log'
[2018-12-07 12:42:09,319] [ERROR] [bogon][getdata.py - line:128] 获取运行的activity异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/acts.log'
[2018-12-07 12:42:09,319] [ERROR] [bogon][getdata.py - line:111] 获取activitys异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/allactivity.log'
[2018-12-07 12:42:09,319] [ERROR] [bogon][getdata.py - line:146] 计算遍历覆盖率异常!float division by zero
[2018-12-07 12:42:09,380] [ERROR] [bogon][getdata.py - line:45] 获取安装耗时数据异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/install_app.log'
[2018-12-07 12:42:09,380] [INFO] [bogon][getdata.py - line:60] 获取冷启动数据异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/lanuch_app.log'
[2018-12-07 12:42:09,381] [ERROR] [bogon][getdata.py - line:93] 获取crash次数异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/crash.log'
[2018-12-07 12:42:09,381] [ERROR] [bogon][getdata.py - line:170] 获取遍历的页面列表异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/acts.log'
[2018-12-07 12:42:09,382] [ERROR] [bogon][getdata.py - line:226] 获取崩溃图片异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/monkey/images'
[2018-12-07 12:42:09,382] [ERROR] [bogon][getdata.py - line:30] 获取登录数据异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/login_app.log'
[2018-12-07 12:42:52,748] [ERROR] [bogon][app.py - line:1761] Exception on /getreport [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/xinxi/PycharmProjects/maxauto/report/server.py", line 55, in html
    data = read_mem()
  File "/Users/xinxi/PycharmProjects/maxauto/report/predata.py", line 41, in read_mem
    with open(mem_path, 'r') as f:
IOError: [Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/mem.log'
[2018-12-07 13:25:30,981] [ERROR] [bogon][app.py - line:1761] Exception on /getreport [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/xinxi/PycharmProjects/maxauto/report/server.py", line 55, in html
    data = read_mem()
  File "/Users/xinxi/PycharmProjects/maxauto/report/predata.py", line 41, in read_mem
    with open(mem_path, 'r') as f:
IOError: [Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/mem.log'
[2018-12-07 14:22:57,965] [ERROR] [bogon][app.py - line:1761] Exception on /getreport [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/xinxi/PycharmProjects/maxauto/report/server.py", line 55, in html
    data = read_mem()
  File "/Users/xinxi/PycharmProjects/maxauto/report/predata.py", line 41, in read_mem
    with open(mem_path, 'r') as f:
IOError: [Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/mem.log'
[2018-12-07 14:23:16,501] [ERROR] [bogon][app.py - line:1761] Exception on /getreport [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/xinxi/PycharmProjects/maxauto/report/server.py", line 69, in html
    data1 = read_cpu()
  File "/Users/xinxi/PycharmProjects/maxauto/report/predata.py", line 25, in read_cpu
    with open(cpu_path, 'r') as f:
IOError: [Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/cpu.log'
[2018-12-07 14:23:40,993] [ERROR] [bogon][app.py - line:1761] Exception on /getreport [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/xinxi/PycharmProjects/maxauto/report/server.py", line 69, in html
    data1 = read_cpu()
  File "/Users/xinxi/PycharmProjects/maxauto/report/predata.py", line 25, in read_cpu
    with open(cpu_path, 'r') as f:
IOError: [Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/cpu.log'
[2018-12-07 14:28:06,150] [ERROR] [bogon][getdata.py - line:111] 获取activitys异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/allactivity.log'
[2018-12-07 14:28:06,151] [ERROR] [bogon][getdata.py - line:146] 计算遍历覆盖率异常!float division by zero
[2018-12-07 14:28:06,471] [ERROR] [bogon][getdata.py - line:45] 获取安装耗时数据异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/install_app.log'
[2018-12-07 14:28:06,471] [INFO] [bogon][getdata.py - line:60] 获取冷启动数据异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/lanuch_app.log'
[2018-12-07 14:28:06,471] [ERROR] [bogon][getdata.py - line:93] 获取crash次数异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/crash.log'
[2018-12-07 14:28:06,480] [ERROR] [bogon][getdata.py - line:226] 获取崩溃图片异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/monkey/images'
[2018-12-07 14:28:06,482] [ERROR] [bogon][getdata.py - line:30] 获取登录数据异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/login_app.log'
[2018-12-07 16:19:58,137] [ERROR] [bogon][getdata.py - line:111] 获取activitys异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/allactivity.log'
[2018-12-07 16:19:58,137] [ERROR] [bogon][getdata.py - line:146] 计算遍历覆盖率异常!float division by zero
[2018-12-07 16:19:58,221] [ERROR] [bogon][getdata.py - line:93] 获取crash次数异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/crash.log'
[2018-12-07 16:19:58,228] [ERROR] [bogon][getdata.py - line:226] 获取崩溃图片异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/monkey/images'
[2018-12-07 16:30:41,547] [INFO] [bogon][server.py - line:32] 启动服务...
[2018-12-07 16:31:11,902] [INFO] [bogon][server.py - line:32] 启动服务...
[2018-12-07 16:31:11,915] [INFO] [bogon][_internal.py - line:88]  * Running on http://127.0.0.1:3031/ (Press CTRL+C to quit)
[2018-12-07 16:31:11,916] [INFO] [bogon][_internal.py - line:88]  * Restarting with stat
[2018-12-07 16:31:12,145] [INFO] [bogon][server.py - line:32] 启动服务...
[2018-12-07 16:31:12,152] [WARNING] [bogon][_internal.py - line:88]  * Debugger is active!
[2018-12-07 16:31:12,181] [INFO] [bogon][_internal.py - line:88]  * Debugger PIN: 120-762-539
[2018-12-07 16:31:41,237] [INFO] [bogon][client.py - line:31] 开始获取报告!
[2018-12-07 16:31:41,310] [ERROR] [bogon][getdata.py - line:111] 获取activitys异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/allactivity.log'
[2018-12-07 16:31:41,310] [ERROR] [bogon][getdata.py - line:146] 计算遍历覆盖率异常!float division by zero
[2018-12-07 16:31:41,369] [ERROR] [bogon][getdata.py - line:93] 获取crash次数异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/crash.log'
[2018-12-07 16:31:41,376] [ERROR] [bogon][getdata.py - line:226] 获取崩溃图片异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/monkey/images'
[2018-12-07 16:31:41,399] [INFO] [bogon][_internal.py - line:88] 127.0.0.1 - - [07/Dec/2018 16:31:41] "POST /getreport HTTP/1.1" 200 -
[2018-12-07 16:31:41,400] [INFO] [bogon][client.py - line:36] 服务端状态码:200
[2018-12-07 16:31:41,401] [INFO] [bogon][client.py - line:40] 报告路径:/Users/xinxi/PycharmProjects/maxauto/report/reports/report_20181207163141.html
[2018-12-07 16:43:19,695] [ERROR] [bogon][server.py - line:65] could not convert string to float: 
[2018-12-07 16:43:19,833] [ERROR] [bogon][getdata.py - line:93] 获取crash次数异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/crash.log'
[2018-12-07 16:43:19,843] [ERROR] [bogon][getdata.py - line:226] 获取崩溃图片异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/monkey/images'
[2018-12-07 17:22:41,836] [ERROR] [bogon][predata.py - line:68] 获取页面数据异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/page.log'
[2018-12-07 17:22:41,883] [ERROR] [bogon][getdata.py - line:128] 获取运行的activity异常!global name 'acts_path' is not defined
[2018-12-07 17:22:41,938] [ERROR] [bogon][getdata.py - line:93] 获取crash次数异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/crash.log'
[2018-12-07 17:22:41,938] [ERROR] [bogon][getdata.py - line:170] 获取遍历的页面列表异常!global name 'acts_path' is not defined
[2018-12-07 17:22:41,938] [ERROR] [bogon][getdata.py - line:226] 获取崩溃图片异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/monkey/images'
[2018-12-07 17:30:36,296] [ERROR] [bogon][predata.py - line:68] 获取页面数据异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/page.log'
[2018-12-07 17:30:36,349] [ERROR] [bogon][getdata.py - line:128] 获取运行的activity异常!global name 'acts_path' is not defined
[2018-12-07 17:30:36,411] [ERROR] [bogon][getdata.py - line:93] 获取crash次数异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/crash.log'
[2018-12-07 17:30:36,411] [ERROR] [bogon][getdata.py - line:170] 获取遍历的页面列表异常!global name 'acts_path' is not defined
[2018-12-07 17:30:36,411] [ERROR] [bogon][getdata.py - line:226] 获取崩溃图片异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/monkey/images'
[2018-12-07 17:44:40,366] [ERROR] [bogon][predata.py - line:68] 获取页面数据异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/page.log'
[2018-12-07 17:44:40,387] [ERROR] [bogon][getdata.py - line:128] 获取运行的activity异常!global name 'acts_path' is not defined
[2018-12-07 17:44:40,444] [ERROR] [bogon][getdata.py - line:93] 获取crash次数异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/crash.log'
[2018-12-07 17:44:40,444] [ERROR] [bogon][getdata.py - line:170] 获取遍历的页面列表异常!global name 'acts_path' is not defined
[2018-12-07 17:44:40,445] [ERROR] [bogon][getdata.py - line:226] 获取崩溃图片异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/monkey/images'
[2018-12-07 17:53:32,396] [ERROR] [bogon][predata.py - line:68] 获取页面数据异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/page.log'
[2018-12-07 17:53:32,418] [ERROR] [bogon][getdata.py - line:128] 获取运行的activity异常!global name 'acts_path' is not defined
[2018-12-07 17:53:32,475] [ERROR] [bogon][getdata.py - line:93] 获取crash次数异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/crash.log'
[2018-12-07 17:53:32,475] [ERROR] [bogon][getdata.py - line:170] 获取遍历的页面列表异常!global name 'acts_path' is not defined
[2018-12-07 17:53:32,475] [ERROR] [bogon][getdata.py - line:226] 获取崩溃图片异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/monkey/images'
[2018-12-07 18:00:25,175] [ERROR] [bogon][server.py - line:65] could not convert string to float: 
[2018-12-07 18:00:25,202] [ERROR] [bogon][getdata.py - line:128] 获取运行的activity异常!global name 'acts_path' is not defined
[2018-12-07 18:00:25,283] [ERROR] [bogon][getdata.py - line:93] 获取crash次数异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/crash.log'
[2018-12-07 18:00:25,284] [ERROR] [bogon][getdata.py - line:170] 获取遍历的页面列表异常!global name 'acts_path' is not defined
[2018-12-07 18:00:25,289] [ERROR] [bogon][getdata.py - line:226] 获取崩溃图片异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/monkey/images'
[2018-12-07 18:11:38,274] [ERROR] [bogon][getdata.py - line:128] 获取运行的activity异常!global name 'acts_path' is not defined
[2018-12-07 18:11:38,330] [ERROR] [bogon][getdata.py - line:93] 获取crash次数异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/crash.log'
[2018-12-07 18:11:38,330] [ERROR] [bogon][getdata.py - line:170] 获取遍历的页面列表异常!global name 'acts_path' is not defined
[2018-12-07 18:11:38,334] [ERROR] [bogon][getdata.py - line:226] 获取崩溃图片异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/monkey/images'
[2018-12-07 18:13:42,952] [INFO] [bogon][server.py - line:32] 启动服务...
[2018-12-07 18:14:19,099] [INFO] [bogon][server.py - line:32] 启动服务...
[2018-12-07 18:14:19,115] [INFO] [bogon][_internal.py - line:88]  * Running on http://127.0.0.1:3031/ (Press CTRL+C to quit)
[2018-12-07 18:14:19,118] [INFO] [bogon][_internal.py - line:88]  * Restarting with stat
[2018-12-07 18:14:19,337] [INFO] [bogon][server.py - line:32] 启动服务...
[2018-12-07 18:14:19,343] [WARNING] [bogon][_internal.py - line:88]  * Debugger is active!
[2018-12-07 18:14:19,366] [INFO] [bogon][_internal.py - line:88]  * Debugger PIN: 120-762-539
[2018-12-07 18:14:55,497] [INFO] [bogon][client.py - line:31] 开始获取报告!
[2018-12-07 18:14:55,536] [ERROR] [bogon][getdata.py - line:128] 获取运行的activity异常!global name 'acts_path' is not defined
[2018-12-07 18:14:55,597] [ERROR] [bogon][getdata.py - line:93] 获取crash次数异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/crash.log'
[2018-12-07 18:14:55,597] [ERROR] [bogon][getdata.py - line:170] 获取遍历的页面列表异常!global name 'acts_path' is not defined
[2018-12-07 18:14:55,602] [ERROR] [bogon][getdata.py - line:226] 获取崩溃图片异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/monkey/images'
[2018-12-07 18:14:55,623] [INFO] [bogon][_internal.py - line:88] 127.0.0.1 - - [07/Dec/2018 18:14:55] "POST /getreport HTTP/1.1" 200 -
[2018-12-07 18:14:55,625] [INFO] [bogon][client.py - line:36] 服务端状态码:200
[2018-12-07 18:14:55,625] [INFO] [bogon][client.py - line:40] 报告路径:/Users/xinxi/PycharmProjects/maxauto/report/reports/report_20181207181455.html
[2018-12-07 18:15:39,443] [INFO] [bogon][_internal.py - line:88]  * Detected change in '/Users/xinxi/PycharmProjects/maxauto/report/getdata.py', reloading
[2018-12-07 18:15:39,497] [INFO] [bogon][_internal.py - line:88]  * Restarting with stat
[2018-12-07 18:15:39,875] [INFO] [bogon][server.py - line:32] 启动服务...
[2018-12-07 18:15:39,889] [WARNING] [bogon][_internal.py - line:88]  * Debugger is active!
[2018-12-07 18:15:39,906] [INFO] [bogon][_internal.py - line:88]  * Debugger PIN: 120-762-539
[2018-12-07 18:15:41,368] [INFO] [bogon][client.py - line:31] 开始获取报告!
[2018-12-07 18:15:41,460] [ERROR] [bogon][getdata.py - line:93] 获取crash次数异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/crash.log'
[2018-12-07 18:15:41,460] [ERROR] [bogon][getdata.py - line:170] 获取遍历的页面列表异常!global name 'acts_path' is not defined
[2018-12-07 18:15:41,465] [ERROR] [bogon][getdata.py - line:226] 获取崩溃图片异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/monkey/images'
[2018-12-07 18:15:41,484] [INFO] [bogon][_internal.py - line:88] 127.0.0.1 - - [07/Dec/2018 18:15:41] "POST /getreport HTTP/1.1" 200 -
[2018-12-07 18:15:41,485] [INFO] [bogon][client.py - line:36] 服务端状态码:200
[2018-12-07 18:15:41,486] [INFO] [bogon][client.py - line:40] 报告路径:/Users/xinxi/PycharmProjects/maxauto/report/reports/report_20181207181541.html
[2018-12-07 18:15:47,501] [INFO] [bogon][server.py - line:32] 启动服务...
[2018-12-07 18:15:47,508] [INFO] [bogon][_internal.py - line:88]  * Running on http://127.0.0.1:3031/ (Press CTRL+C to quit)
[2018-12-07 18:15:47,509] [INFO] [bogon][_internal.py - line:88]  * Restarting with stat
[2018-12-07 18:15:47,744] [INFO] [bogon][server.py - line:32] 启动服务...
[2018-12-07 18:15:47,752] [WARNING] [bogon][_internal.py - line:88]  * Debugger is active!
[2018-12-07 18:15:47,766] [INFO] [bogon][_internal.py - line:88]  * Debugger PIN: 120-762-539
[2018-12-07 18:15:49,609] [INFO] [bogon][client.py - line:31] 开始获取报告!
[2018-12-07 18:15:49,682] [ERROR] [bogon][getdata.py - line:93] 获取crash次数异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/crash.log'
[2018-12-07 18:15:49,682] [ERROR] [bogon][getdata.py - line:170] 获取遍历的页面列表异常!global name 'acts_path' is not defined
[2018-12-07 18:15:49,686] [ERROR] [bogon][getdata.py - line:226] 获取崩溃图片异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/monkey/images'
[2018-12-07 18:15:49,703] [INFO] [bogon][_internal.py - line:88] 127.0.0.1 - - [07/Dec/2018 18:15:49] "POST /getreport HTTP/1.1" 200 -
[2018-12-07 18:15:49,705] [INFO] [bogon][client.py - line:36] 服务端状态码:200
[2018-12-07 18:15:49,705] [INFO] [bogon][client.py - line:40] 报告路径:/Users/xinxi/PycharmProjects/maxauto/report/reports/report_20181207181549.html
[2018-12-07 18:16:03,982] [INFO] [bogon][_internal.py - line:88]  * Detected change in '/Users/xinxi/PycharmProjects/maxauto/report/getdata.py', reloading
[2018-12-07 18:16:04,003] [INFO] [bogon][_internal.py - line:88]  * Restarting with stat
[2018-12-07 18:16:04,297] [INFO] [bogon][server.py - line:32] 启动服务...
[2018-12-07 18:16:04,305] [WARNING] [bogon][_internal.py - line:88]  * Debugger is active!
[2018-12-07 18:16:04,323] [INFO] [bogon][_internal.py - line:88]  * Debugger PIN: 120-762-539
[2018-12-07 18:16:07,322] [INFO] [bogon][client.py - line:31] 开始获取报告!
[2018-12-07 18:16:07,411] [ERROR] [bogon][getdata.py - line:93] 获取crash次数异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/crash.log'
[2018-12-07 18:16:07,416] [ERROR] [bogon][getdata.py - line:226] 获取崩溃图片异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/monkey/images'
[2018-12-07 18:16:07,437] [INFO] [bogon][_internal.py - line:88] 127.0.0.1 - - [07/Dec/2018 18:16:07] "POST /getreport HTTP/1.1" 200 -
[2018-12-07 18:16:07,438] [INFO] [bogon][client.py - line:36] 服务端状态码:200
[2018-12-07 18:16:07,439] [INFO] [bogon][client.py - line:40] 报告路径:/Users/xinxi/PycharmProjects/maxauto/report/reports/report_20181207181607.html
[2018-12-07 18:22:50,359] [ERROR] [bogon][getdata.py - line:93] 获取crash次数异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/crash.log'
[2018-12-07 18:22:50,362] [ERROR] [bogon][getdata.py - line:226] 获取崩溃图片异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/monkey/images'
[2018-12-07 18:39:08,390] [ERROR] [bogon][server.py - line:65] could not convert string to float: 
[2018-12-07 18:39:08,570] [ERROR] [bogon][getdata.py - line:45] 获取安装耗时数据异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/install_app.log'
[2018-12-07 18:39:08,571] [INFO] [bogon][getdata.py - line:60] 获取冷启动数据异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/lanuch_app.log'
[2018-12-07 18:39:08,571] [ERROR] [bogon][getdata.py - line:93] 获取crash次数异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/crash.log'
[2018-12-07 18:39:08,577] [ERROR] [bogon][getdata.py - line:226] 获取崩溃图片异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/monkey/images'
[2018-12-07 18:39:08,578] [ERROR] [bogon][getdata.py - line:30] 获取登录数据异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/login_app.log'
[2018-12-07 18:43:04,843] [ERROR] [bogon][predata.py - line:68] 获取页面数据异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/page.log'
[2018-12-07 18:43:04,855] [ERROR] [bogon][getdata.py - line:128] 获取运行的activity异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/runactivity.log'
[2018-12-07 18:43:04,978] [ERROR] [bogon][getdata.py - line:45] 获取安装耗时数据异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/install_app.log'
[2018-12-07 18:43:04,979] [INFO] [bogon][getdata.py - line:60] 获取冷启动数据异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/lanuch_app.log'
[2018-12-07 18:43:04,979] [ERROR] [bogon][getdata.py - line:93] 获取crash次数异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/crash.log'
[2018-12-07 18:43:04,980] [ERROR] [bogon][getdata.py - line:170] 获取遍历的页面列表异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/runactivity.log'
[2018-12-07 18:43:04,980] [ERROR] [bogon][getdata.py - line:226] 获取崩溃图片异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/monkey/images'
[2018-12-07 18:43:04,981] [ERROR] [bogon][getdata.py - line:30] 获取登录数据异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/login_app.log'
[2018-12-07 19:10:27,881] [ERROR] [bogon][getdata.py - line:45] 获取安装耗时数据异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/install_app.log'
[2018-12-07 19:10:27,882] [INFO] [bogon][getdata.py - line:60] 获取冷启动数据异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/lanuch_app.log'
[2018-12-07 19:10:27,882] [ERROR] [bogon][getdata.py - line:93] 获取crash次数异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/crash.log'
[2018-12-07 19:10:27,886] [ERROR] [bogon][getdata.py - line:226] 获取崩溃图片异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/monkey/images'
[2018-12-07 19:10:27,887] [ERROR] [bogon][getdata.py - line:30] 获取登录数据异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/login_app.log'
[2018-12-07 19:34:44,732] [INFO] [bogon][server.py - line:32] 启动服务...
[2018-12-07 19:35:13,444] [INFO] [bogon][server.py - line:32] 启动服务...
[2018-12-07 19:35:13,458] [INFO] [bogon][_internal.py - line:88]  * Running on http://127.0.0.1:3031/ (Press CTRL+C to quit)
[2018-12-07 19:35:13,459] [INFO] [bogon][_internal.py - line:88]  * Restarting with stat
[2018-12-07 19:35:13,681] [INFO] [bogon][server.py - line:32] 启动服务...
[2018-12-07 19:35:13,687] [WARNING] [bogon][_internal.py - line:88]  * Debugger is active!
[2018-12-07 19:35:13,715] [INFO] [bogon][_internal.py - line:88]  * Debugger PIN: 120-762-539
[2018-12-07 19:35:19,100] [INFO] [bogon][client.py - line:31] 开始获取报告!
[2018-12-07 19:35:19,212] [ERROR] [bogon][getdata.py - line:45] 获取安装耗时数据异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/install_app.log'
[2018-12-07 19:35:19,213] [INFO] [bogon][getdata.py - line:60] 获取冷启动数据异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/lanuch_app.log'
[2018-12-07 19:35:19,213] [ERROR] [bogon][getdata.py - line:93] 获取crash次数异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/crash.log'
[2018-12-07 19:35:19,218] [ERROR] [bogon][getdata.py - line:226] 获取崩溃图片异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/monkey/images'
[2018-12-07 19:35:19,218] [ERROR] [bogon][getdata.py - line:30] 获取登录数据异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/login_app.log'
[2018-12-07 19:35:19,240] [INFO] [bogon][_internal.py - line:88] 127.0.0.1 - - [07/Dec/2018 19:35:19] "POST /getreport HTTP/1.1" 200 -
[2018-12-07 19:35:19,241] [INFO] [bogon][client.py - line:36] 服务端状态码:200
[2018-12-07 19:35:19,242] [INFO] [bogon][client.py - line:40] 报告路径:/Users/xinxi/PycharmProjects/maxauto/report/reports/report_20181207193519.html
[2018-12-07 19:39:28,602] [INFO] [bogon][client.py - line:31] 开始获取报告!
[2018-12-07 19:39:28,714] [ERROR] [bogon][getdata.py - line:45] 获取安装耗时数据异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/install_app.log'
[2018-12-07 19:39:28,715] [INFO] [bogon][getdata.py - line:60] 获取冷启动数据异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/lanuch_app.log'
[2018-12-07 19:39:28,715] [ERROR] [bogon][getdata.py - line:93] 获取crash次数异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/crash.log'
[2018-12-07 19:39:28,720] [ERROR] [bogon][getdata.py - line:226] 获取崩溃图片异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/monkey/images'
[2018-12-07 19:39:28,720] [ERROR] [bogon][getdata.py - line:30] 获取登录数据异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/login_app.log'
[2018-12-07 19:39:28,746] [INFO] [bogon][_internal.py - line:88] 127.0.0.1 - - [07/Dec/2018 19:39:28] "POST /getreport HTTP/1.1" 200 -
[2018-12-07 19:39:28,747] [INFO] [bogon][client.py - line:36] 服务端状态码:200
[2018-12-07 19:39:28,749] [INFO] [bogon][client.py - line:40] 报告路径:/Users/xinxi/PycharmProjects/maxauto/report/reports/report_20181207193928.html
[2018-12-07 19:41:42,612] [INFO] [bogon][client.py - line:31] 开始获取报告!
[2018-12-07 19:41:42,721] [ERROR] [bogon][getdata.py - line:45] 获取安装耗时数据异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/install_app.log'
[2018-12-07 19:41:42,721] [INFO] [bogon][getdata.py - line:60] 获取冷启动数据异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/lanuch_app.log'
[2018-12-07 19:41:42,721] [ERROR] [bogon][getdata.py - line:93] 获取crash次数异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/crash.log'
[2018-12-07 19:41:42,726] [ERROR] [bogon][getdata.py - line:226] 获取崩溃图片异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/monkey/images'
[2018-12-07 19:41:42,726] [ERROR] [bogon][getdata.py - line:30] 获取登录数据异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/login_app.log'
[2018-12-07 19:41:42,728] [INFO] [bogon][_internal.py - line:88] 127.0.0.1 - - [07/Dec/2018 19:41:42] "POST /getreport HTTP/1.1" 200 -
[2018-12-07 19:41:42,729] [INFO] [bogon][client.py - line:36] 服务端状态码:200
[2018-12-07 19:41:42,729] [INFO] [bogon][client.py - line:40] 报告路径:/Users/xinxi/PycharmProjects/maxauto/report/reports/report_20181207194142.html
[2018-12-07 19:41:42,757] [INFO] [bogon][_internal.py - line:88]  * Detected change in '/Users/xinxi/PycharmProjects/maxauto/report/server.py', reloading
[2018-12-07 19:41:42,791] [INFO] [bogon][_internal.py - line:88]  * Restarting with stat
[2018-12-07 19:41:43,033] [INFO] [bogon][server.py - line:32] 启动服务...
[2018-12-07 19:41:43,047] [WARNING] [bogon][_internal.py - line:88]  * Debugger is active!
[2018-12-07 19:41:43,067] [INFO] [bogon][_internal.py - line:88]  * Debugger PIN: 120-762-539
[2018-12-07 19:42:03,800] [INFO] [bogon][client.py - line:31] 开始获取报告!
[2018-12-07 19:42:03,905] [ERROR] [bogon][getdata.py - line:45] 获取安装耗时数据异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/install_app.log'
[2018-12-07 19:42:03,905] [INFO] [bogon][getdata.py - line:60] 获取冷启动数据异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/lanuch_app.log'
[2018-12-07 19:42:03,906] [ERROR] [bogon][getdata.py - line:93] 获取crash次数异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/crash.log'
[2018-12-07 19:42:03,910] [ERROR] [bogon][getdata.py - line:226] 获取崩溃图片异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/monkey/images'
[2018-12-07 19:42:03,910] [ERROR] [bogon][getdata.py - line:30] 获取登录数据异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/login_app.log'
[2018-12-07 19:42:03,933] [INFO] [bogon][_internal.py - line:88] 127.0.0.1 - - [07/Dec/2018 19:42:03] "POST /getreport HTTP/1.1" 200 -
[2018-12-07 19:42:03,934] [INFO] [bogon][client.py - line:36] 服务端状态码:200
[2018-12-07 19:42:03,934] [INFO] [bogon][client.py - line:40] 报告路径:/Users/xinxi/PycharmProjects/maxauto/report/reports/report_20181207194203.html
[2018-12-07 19:43:12,454] [INFO] [bogon][server.py - line:32] 启动服务...
[2018-12-07 19:43:12,469] [INFO] [bogon][_internal.py - line:88]  * Running on http://127.0.0.1:3031/ (Press CTRL+C to quit)
[2018-12-07 19:43:12,470] [INFO] [bogon][_internal.py - line:88]  * Restarting with stat
[2018-12-07 19:43:12,675] [INFO] [bogon][server.py - line:32] 启动服务...
[2018-12-07 19:43:12,682] [WARNING] [bogon][_internal.py - line:88]  * Debugger is active!
[2018-12-07 19:43:12,700] [INFO] [bogon][_internal.py - line:88]  * Debugger PIN: 120-762-539
[2018-12-07 19:43:13,631] [INFO] [bogon][client.py - line:31] 开始获取报告!
[2018-12-07 19:43:13,737] [ERROR] [bogon][getdata.py - line:45] 获取安装耗时数据异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/install_app.log'
[2018-12-07 19:43:13,737] [INFO] [bogon][getdata.py - line:60] 获取冷启动数据异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/lanuch_app.log'
[2018-12-07 19:43:13,737] [ERROR] [bogon][getdata.py - line:93] 获取crash次数异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/crash.log'
[2018-12-07 19:43:13,743] [ERROR] [bogon][getdata.py - line:226] 获取崩溃图片异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/monkey/images'
[2018-12-07 19:43:13,743] [ERROR] [bogon][getdata.py - line:30] 获取登录数据异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/login_app.log'
[2018-12-07 19:43:13,765] [INFO] [bogon][_internal.py - line:88] 127.0.0.1 - - [07/Dec/2018 19:43:13] "POST /getreport HTTP/1.1" 200 -
[2018-12-07 19:43:13,766] [INFO] [bogon][client.py - line:36] 服务端状态码:200
[2018-12-07 19:43:13,766] [INFO] [bogon][client.py - line:40] 报告路径:/Users/xinxi/PycharmProjects/maxauto/report/reports/report_20181207194313.html
[2018-12-07 19:50:41,464] [ERROR] [bogon][getdata.py - line:93] 获取crash次数异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/crash.log'
[2018-12-07 19:50:41,478] [ERROR] [bogon][getdata.py - line:226] 获取崩溃图片异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/monkey/images'
